# Generated by Django 5.0.7 on 2025-09-04 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('gym', 'Gym'), ('business', 'Business'), ('standalone', 'Standalone')], max_length=50)),
                ('contact_info', models.JSONField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('subscription_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('end_user_count', models.IntegerField(default=0)),
                ('device_count', models.IntegerField(default=0)),
                ('database_connection_string', models.TextField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_type', models.CharField(choices=[('gym_portal', 'Gym Portal'), ('business_manager', 'Business Manager'), ('standalone', 'Standalone')], max_length=50)),
                ('admin_level', models.CharField(choices=[('property_manager', 'Property Manager'), ('sub_account', 'Sub Account')], default='property_manager', max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('parent_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationadmin')),
            ],
            options={
                'db_table': 'organization_admins',
                'unique_together': {('organization', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_category', models.CharField(choices=[('billing', 'Billing'), ('service_provider', 'Service Provider'), ('notification', 'Notification'), ('security', 'Security'), ('general', 'General')], max_length=50)),
                ('setting_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organizationadmin')),
            ],
            options={
                'db_table': 'organization_settings',
                'unique_together': {('organization', 'setting_category')},
            },
        ),
    ]
