# Generated by Django 5.0.7 on 2025-09-03 13:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('organization_id', models.UUIDField(blank=True, help_text='Organization this user belongs to', null=True)),
                ('email', models.CharField(help_text="User's email address (used for login)", max_length=255, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', help_text='Hashed password', max_length=255)),
                ('full_name', models.CharField(help_text="User's full name", max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=30, null=True)),
                ('user_type', models.CharField(help_text="User's role type (ADMIN, MANAGER, EMPLOYEE, HR, etc.)", max_length=50)),
                ('status', models.CharField(help_text="User's current status (ACTIVE, INACTIVE, SUSPENDED, etc.)", max_length=50)),
                ('subscription_details', models.JSONField(blank=True, default=dict, help_text="User's subscription information")),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='Emergency contact information')),
                ('profile_image_url', models.TextField(blank=True, help_text="URL to user's profile image", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when user was created')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('created_by', models.UUIDField(blank=True, help_text='ID of user who created this account', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
